### ISSUE TITLE
Default DuckDuckGo to search for 'All regions' from 'United States'

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#10]
Perhaps it is unique to my machine, but right now all the searches made with Searchio for DuckDuckGo are scoped to 'United States' : 

![2017-01-28 at 13 33](https://cloud.githubusercontent.com/assets/6391776/22396633/6b5fe708-e55e-11e6-8232-3a02f24a4793.png)

This for some reason turns off '[instant answers](https://duck.co/help/features/instant-answers-and-other-features)' feature. However when you change the search to 'All Regions', instant answers comes back : 

![2017-01-28 at 13 35](https://cloud.githubusercontent.com/assets/6391776/22396640/b7da99b6-e55e-11e6-9aca-3998b165aa05.png)

**Comment by deanishe** [comment]
This is an issue with DDG, not the workflow.

**Comment by nikitavoloboev** [comment]
This is fixed by changing [this line](https://github.com/deanishe/alfred-searchio/blob/master/src/search.py#L493) to this : 

```python
query = query.format(self.options['lang'])
```

Now all instant answers work. :) 

I guess there is no need for pull request as there is a new version in the works.
