### ISSUE TITLE
Bing search adds on 'language:en' to all searches 

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#12]
Searching for and clicking on this result : 

![2017-03-12 at 13 31](https://cloud.githubusercontent.com/assets/6391776/23831784/32fc86fa-0728-11e7-9a3b-0c2dec201b67.png)

Searches for : 

![2017-03-12 at 13 31](https://cloud.githubusercontent.com/assets/6391776/23831788/3edddd8e-0728-11e7-85ae-c21f8a5f18ac.png)

It doesn't seem to affect results but still quite strange I think that it does it.

**Comment by deanishe** [comment]
Of course it doesn't affect the results when it's the same language as you have Bing set to…

**Comment by nikitavoloboev** [comment]
Yeah, I understand, I just thought it was a bug since no other search engine does such a thing. 

Changing this would be mostly to just improve the aesthetics of the search so never mind the issue as it doesn't affect functionality in any way.

**Comment by deanishe** [comment]
Other search engines have URL parameters for setting the language. Bing doesn't appear to support that feature, so the language has to be specified via the query.
