### ISSUE TITLE
Would it be possible to reach the same speed as Anycomplete on Google searches?

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#13]
There is a [really cool plugin](https://github.com/pdaddyo/anycomplete) for Hammerspoon that allows google searching. Although it only autocompletes queries for quick typing. 

The speed of it though is much much faster than searchio. I am curious, whether it is possible to have Searchio autocomplete results this fast?

Thank you a lot for this workflow.

**Comment by deanishe** [comment]
> I am curious, whether it is possible to have Searchio autocomplete results this fast?

Sure. Rewrite the workflow in Swift or Go.
