### ISSUE TITLE
Not working on MacOS Sierra

### ISSUE THREAD

**Issue by claudioruiz** [deanishe/alfred-searchio#14]
![image](https://user-images.githubusercontent.com/390030/28582460-799476c0-7133-11e7-86cd-cd56821ab9e0.png)

Apparently, because is using [an incompatible Python workflow library](https://www.alfredapp.com/help/troubleshooting/incompatible-python-workflow-library/)

**Comment by deanishe** [comment]
The fix didn't work?

**Comment by claudioruiz** [comment]
I didn't know about the fix. Now _fixed_

**Comment by deanishe** [comment]
The screenshot and link you posted explain the fix ;)
