### ISSUE TITLE
v2 feature request to add 'I am lucky' to google search

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#15]
Not sure if there is API for this but it would be quite awesome if you could on google search results with a modifier key do the 'I am lucky' option. 

It would be especially useful when you know what the first result will look like so will save you going to google page and going to the result from there.

**Comment by duqcyxwd** [comment]
I think I just got a PR for this feature.

**Comment by nikitavoloboev** [comment]
Yeah I saw it. However yours adds a separate search for it. I wanted it as a modifier key press to the normal google search searchio provides. 

So ⏎ will search on google and ⌃ + ⏎ will do `I am lucky` search on result.

**Comment by deanishe** [comment]
I'm not going to add an alternate search.

As best as I can tell, it's only useful on Google, and I don't really see much benefit to it: If you want the "I'm feeling lucky" search, why didn't you use that one to begin with?

**Comment by nikitavoloboev** [comment]
> If you want the "I'm feeling lucky" search, why didn't you use that one to begin with?

I just wanted to keep Google Search to one trigger. Because the suggestions are the same, I just can choose to to open results in the web page or trigger Lucky Search. For me its a lot cleaner to have the latter be done with a modifier press than an entire new script filter with a trigger.
