### ISSUE TITLE
Packal version is outdated

### ISSUE THREAD

**Issue by vitorgalvao** [deanishe/alfred-searchio#2]
Even though both [the version on packal](http://www.packal.org/workflow/searchio) and [the one on github](https://github.com/deanishe/alfred-searchio/releases) were released on the same day (January 19<sup>th</sup>), the version on packal is 1.5 while the one on github is 1.6.1.

**Comment by deanishe** [comment]
I've updated the Packal version to match. Thanks very much for the heads-up.
