### ISSUE TITLE
Include the actual text I'm typing in the list of suggestions

### ISSUE THREAD

**Issue by ole** [deanishe/alfred-searchio#20]
Thanks a lot for this workflow, I love it!

My only occasional issue is that the list of suggested search terms doesn't include the term I actually typed. Sometimes it happens that the autocomplete suggestions are not what I meant so I'd like to search for the exact term I typed.

Example: I want to search for "nintendo", but I can't because all suggestions have been eagerly extended:

<img width="573" alt="screen shot 2017-10-26 at 12 27 14" src="https://user-images.githubusercontent.com/5010/32048299-59acea0e-ba49-11e7-8c75-b6315f942ad9.png">

This behavior is different from most autosuggest implementations on the web, which almost always list the stuff you typed as the first option in the list of suggestions.

Is there an option to get this behavior for this workflow? If not, would it be possible to add one?

**Comment by nikitavoloboev** [comment]
It should be a matter of changing [this line](https://github.com/deanishe/alfred-searchio/blob/master/src/search.py#L204). For me I have the code as in this repo and my query is always the first result : 

![2017-10-26 at 13 18](https://user-images.githubusercontent.com/6391776/32050196-3d0b894e-ba50-11e7-910f-c5e1dc21bbc5.png)

**Comment by ole** [comment]
@nikitavoloboev Thanks, your comment prompted me to look for a setting again. And I found it. Setting "Show query results in query" to Yes is what I want:

<img width="573" alt="screen shot 2017-10-26 at 16 21 01" src="https://user-images.githubusercontent.com/5010/32058257-d5e25d82-ba69-11e7-8e08-436464e0eef0.png">

**Comment by deanishe** [comment]
> changing this line.

Wrong.

> Setting "Show query in results" to Yes is what I want

Right.

FWIW, v2 follows @nikitavoloboev's suggestion of including the user query at the end, so it won't be in your face, but hitting ↑ will immediately go to it.

**Comment by nikitavoloboev** [comment]
> including the user query at the end

Would this be configurable? As I quite like having the query be the first result as often times it is the query I am typing I want to search, not the suggestion.

**Comment by deanishe** [comment]
> Would this be configurable?

Probably not. The whole point of the workflow is the suggestions. It you just want to enter a query, well, that's what Alfred's own web searches are for.
