### ISSUE TITLE
Can inline Alfred searches be added?

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#29]
It would be awesome if you could see results of queries inside Alfred itself. Like for example in [this GIF](https://camo.githubusercontent.com/e379e2cb3564a0d048a6e6d02dd189a5b804017d/68747470733a2f2f7468756d62732e6766796361742e636f6d2f426c6f6e644c696e6564476e6174636174636865722d6d61782d31346d622e676966) (Have to skip to the end).

This is for Albert launcher but it can transferred to Alfred too. [Here](https://github.com/nglgzz/albert-plugins/blob/master/google.py) is the code for Google inline search and [here](https://github.com/nglgzz/albert-plugins/blob/master/youtube.py) is for YouTube.

Would it be possible to add support for inline searching too in this workflow?

In that implementation `_` symbol anywhere in the query triggers inline search. You can also trigger inline search with a modifier so if you ⌃ + ⏎ on a query, it will show results for the query inline in Alfred thus saving the loading time of the entire web page and selecting of result there.

**Comment by deanishe** [comment]
No. Showing inline results isn't really a goal of this workflow.

I may consider it in future, such as for GitHub #22, which has an API for that, but *not* when it involves parsing HTML.

It breaks too easily and would be damn difficult now the engines are defined by JSON files, not Python classes.
