### ISSUE TITLE
Weird error when trying to use the workflow.

### ISSUE THREAD

**Issue by brianroach** [deanishe/alfred-searchio#3]
This happens with any search criteria with any search engine.

![2016-02-19 at 4 45 pm](https://cloud.githubusercontent.com/assets/9772694/13193115/4ae2bf72-d728-11e5-9338-df1a361fd9ce.jpg)

**Comment by brianroach** [comment]
Starting` debug for 'Searchio!'

[ERROR: alfred.workflow.input.scriptfilter] Code 1: 14:59:46 workflow.py:1972 DEBUG    Workflow version : 1.8.0
14:59:46 workflow.py:1387 DEBUG    Reading settings from `/Users/anodigital/Library/Application Support/Alfred 2/Workflow Data/net.deanishe.alfred-searchio/settings.json` ...
14:59:46 workflow.py:2233 DEBUG    Update check not due
14:59:46 search.py:518 DEBUG    subclass : Yandex.ru
14:59:46 search.py:518 DEBUG    subclass : Naver.com
14:59:46 search.py:518 DEBUG    subclass : Google
14:59:46 search.py:518 DEBUG    subclass : Google Images
14:59:46 search.py:518 DEBUG    subclass : Google Maps
14:59:46 search.py:518 DEBUG    subclass : YouTube
14:59:46 search.py:518 DEBUG    subclass : Amazon
14:59:46 search.py:518 DEBUG    subclass : eBay
14:59:46 search.py:518 DEBUG    subclass : Bing
14:59:46 search.py:518 DEBUG    subclass : Yahoo!
14:59:46 search.py:518 DEBUG    subclass : DuckDuckGo
14:59:46 search.py:518 DEBUG    subclass : Wiktionary
14:59:46 search.py:518 DEBUG    subclass : Wikipedia
14:59:46 search.py:518 DEBUG    subclass : Wikia
14:59:46 search.py:518 DEBUG    subclass : Ask
14:59:46 workflow.py:1610 DEBUG    Loading cached data from : /Users/anodigital/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/net.deanishe.alfred-searchio/__workflow_update_status.cpickle
14:59:46 workflow.py:2181 DEBUG    update_data : {u'available': False}
2016-02-21 14:59:46.904 defaults[68855:1228259] 
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist
14:59:46 workflow.py:1990 ERROR    Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/Users/anodigital/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.D637B5EC-7C86-4E7A-B210-673FE30A3E52/workflow/workflow.py", line 1983, in run
    func(self)
  File "search.py", line 598, in main
    max_age=3600)
  File "/Users/anodigital/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.D637B5EC-7C86-4E7A-B210-673FE30A3E52/workflow/workflow.py", line 1616, in cached_data
    data = data_func()
  File "search.py", line 58, in get_system_language
    output = check_output(['defaults', 'read', '-g', 'AppleLanguages'])
  File "search.py", line 50, in check_output
    return subprocess.check_output(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1
14:59:46 workflow.py:1993 INFO     For assistance, see: https://github.com/deanishe/alfred-searchio/issues
14:59:46 workflow.py:2008 DEBUG    Workflow finished in 0.016 seconds.
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'net.deanishe.alfred-searchio'</title><subtitle>Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 14:59:47 workflow.py:1972 DEBUG    Workflow version : 1.8.0
14:59:47 workflow.py:1387 DEBUG    Reading settings from `/Users/anodigital/Library/Application Support/Alfred 2/Workflow Data/net.deanishe.alfred-searchio/settings.json` ...
14:59:47 workflow.py:2233 DEBUG    Update check not due
14:59:47 search.py:518 DEBUG    subclass : Yandex.ru
14:59:47 search.py:518 DEBUG    subclass : Naver.com
14:59:47 search.py:518 DEBUG    subclass : Google
14:59:47 search.py:518 DEBUG    subclass : Google Images
14:59:47 search.py:518 DEBUG    subclass : Google Maps
14:59:47 search.py:518 DEBUG    subclass : YouTube
14:59:47 search.py:518 DEBUG    subclass : Amazon
14:59:47 search.py:518 DEBUG    subclass : eBay
14:59:47 search.py:518 DEBUG    subclass : Bing
14:59:47 search.py:518 DEBUG    subclass : Yahoo!
14:59:47 search.py:518 DEBUG    subclass : DuckDuckGo
14:59:47 search.py:518 DEBUG    subclass : Wiktionary
14:59:47 search.py:518 DEBUG    subclass : Wikipedia
14:59:47 search.py:518 DEBUG    subclass : Wikia
14:59:47 search.py:518 DEBUG    subclass : Ask
14:59:47 workflow.py:1610 DEBUG    Loading cached data from : /Users/anodigital/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/net.deanishe.alfred-searchio/__workflow_update_status.cpickle
14:59:47 workflow.py:2181 DEBUG    update_data : {u'available': False}
2016-02-21 14:59:47.126 defaults[68857:1228277] 
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist
14:59:47 workflow.py:1990 ERROR    Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/Users/anodigital/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.D637B5EC-7C86-4E7A-B210-673FE30A3E52/workflow/workflow.py", line 1983, in run
    func(self)
  File "search.py", line 598, in main
    max_age=3600)
  File "/Users/anodigital/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.D637B5EC-7C86-4E7A-B210-673FE30A3E52/workflow/workflow.py", line 1616, in cached_data
    data = data_func()
  File "search.py", line 58, in get_system_language
    output = check_output(['defaults', 'read', '-g', 'AppleLanguages'])
  File "search.py", line 50, in check_output
    return subprocess.check_output(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1
14:59:47 workflow.py:1993 INFO     For assistance, see: https://github.com/deanishe/alfred-searchio/issues
14:59:47 workflow.py:2008 DEBUG    Workflow finished in 0.019 seconds.
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'net.deanishe.alfred-searchio'</title><subtitle>Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 14:59:47 workflow.py:1972 DEBUG    Workflow version : 1.8.0
14:59:47 workflow.py:1387 DEBUG    Reading settings from `/Users/anodigital/Library/Application Support/Alfred 2/Workflow Data/net.deanishe.alfred-searchio/settings.json` ...
14:59:47 workflow.py:2233 DEBUG    Update check not due
14:59:47 search.py:518 DEBUG    subclass : Yandex.ru
14:59:47 search.py:518 DEBUG    subclass : Naver.com
14:59:47 search.py:518 DEBUG    subclass : Google
14:59:47 search.py:518 DEBUG    subclass : Google Images
14:59:47 search.py:518 DEBUG    subclass : Google Maps
14:59:47 search.py:518 DEBUG    subclass : YouTube
14:59:47 search.py:518 DEBUG    subclass : Amazon
14:59:47 search.py:518 DEBUG    subclass : eBay
14:59:47 search.py:518 DEBUG    subclass : Bing
14:59:47 search.py:518 DEBUG    subclass : Yahoo!
14:59:47 search.py:518 DEBUG    subclass : DuckDuckGo
14:59:47 search.py:518 DEBUG    subclass : Wiktionary
14:59:47 search.py:518 DEBUG    subclass : Wikipedia
14:59:47 search.py:518 DEBUG    subclass : Wikia
14:59:47 search.py:518 DEBUG    subclass : Ask
14:59:47 workflow.py:1610 DEBUG    Loading cached data from : /Users/anodigital/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/net.deanishe.alfred-searchio/__workflow_update_status.cpickle
14:59:47 workflow.py:2181 DEBUG    update_data : {u'available': False}
2016-02-21 14:59:47.281 defaults[68859:1228283] 
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist
14:59:47 workflow.py:1990 ERROR    Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/Users/anodigital/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.D637B5EC-7C86-4E7A-B210-673FE30A3E52/workflow/workflow.py", line 1983, in run
    func(self)
  File "search.py", line 598, in main
    max_age=3600)
  File "/Users/anodigital/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.D637B5EC-7C86-4E7A-B210-673FE30A3E52/workflow/workflow.py", line 1616, in cached_data
    data = data_func()
  File "search.py", line 58, in get_system_language
    output = check_output(['defaults', 'read', '-g', 'AppleLanguages'])
  File "search.py", line 50, in check_output
    return subprocess.check_output(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1
14:59:47 workflow.py:1993 INFO     For assistance, see: https://github.com/deanishe/alfred-searchio/issues
14:59:47 workflow.py:2008 DEBUG    Workflow finished in 0.017 seconds.
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'net.deanishe.alfred-searchio'</title><subtitle>Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 14:59:47 workflow.py:1972 DEBUG    Workflow version : 1.8.0
14:59:47 workflow.py:1387 DEBUG    Reading settings from `/Users/anodigital/Library/Application Support/Alfred 2/Workflow Data/net.deanishe.alfred-searchio/settings.json` ...
14:59:47 workflow.py:2233 DEBUG    Update check not due
14:59:47 search.py:518 DEBUG    subclass : Yandex.ru
14:59:47 search.py:518 DEBUG    subclass : Naver.com
14:59:47 search.py:518 DEBUG    subclass : Google
14:59:47 search.py:518 DEBUG    subclass : Google Images
14:59:47 search.py:518 DEBUG    subclass : Google Maps
14:59:47 search.py:518 DEBUG    subclass : YouTube
14:59:47 search.py:518 DEBUG    subclass : Amazon
14:59:47 search.py:518 DEBUG    subclass : eBay
14:59:47 search.py:518 DEBUG    subclass : Bing
14:59:47 search.py:518 DEBUG    subclass : Yahoo!
14:59:47 search.py:518 DEBUG    subclass : DuckDuckGo
14:59:47 search.py:518 DEBUG    subclass : Wiktionary
14:59:47 search.py:518 DEBUG    subclass : Wikipedia
14:59:47 search.py:518 DEBUG    subclass : Wikia
14:59:47 search.py:518 DEBUG    subclass : Ask
14:59:47 workflow.py:1610 DEBUG    Loading cached data from : /Users/anodigital/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/net.deanishe.alfred-searchio/__workflow_update_status.cpickle
14:59:47 workflow.py:2181 DEBUG    update_data : {u'available': False}
2016-02-21 14:59:47.428 defaults[68861:1228289] 
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist
14:59:47 workflow.py:1990 ERROR    Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/Users/anodigital/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.D637B5EC-7C86-4E7A-B210-673FE30A3E52/workflow/workflow.py", line 1983, in run
    func(self)
  File "search.py", line 598, in main
    max_age=3600)
  File "/Users/anodigital/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.D637B5EC-7C86-4E7A-B210-673FE30A3E52/workflow/workflow.py", line 1616, in cached_data
    data = data_func()
  File "search.py", line 58, in get_system_language
    output = check_output(['defaults', 'read', '-g', 'AppleLanguages'])
  File "search.py", line 50, in check_output
    return subprocess.check_output(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1
14:59:47 workflow.py:1993 INFO     For assistance, see: https://github.com/deanishe/alfred-searchio/issues
14:59:47 workflow.py:2008 DEBUG    Workflow finished in 0.016 seconds.
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'net.deanishe.alfred-searchio'</title><subtitle>Command '[u'defaults', u'read', u'-g', u'AppleLanguages']' returned non-zero exit status 1</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>

**Comment by deanishe** [comment]
Thanks. There appears to be an issue with your system settings.

Could you try running `defaults read -g AppleLanguages` in Terminal/iTerm? This will probably fail (that appears to be what's causing the issue).

Could you also tell me what preferred language(s) and region you have set in `System Preferences > Language & Region`?

I don't know what the cause of the error could be, but it appears to be coming from that direction.

**Comment by brianroach** [comment]
Thanks for your help!

Here is the output:

`2016-02-26 14:09:45.902 defaults[25173:16640432] 
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist`

Language & Region settings:

![2016-02-26 at 2 11 pm](https://cloud.githubusercontent.com/assets/9772694/13366855/c9258882-dc92-11e5-89fa-9ac9b5a39d0b.jpg)

**Comment by deanishe** [comment]
Could you try adding a second language to your `Preferred languages`, e.g. British English.

Then see if `defaults read -g AppleLanguages` outputs anything?

At any rate, I'll fix the workflow to default to `en_US` if no `AppleLanguages` are set.

**Comment by deanishe** [comment]
Great.
