### ISSUE TITLE
Leave a bit off space between Script Filters generated and the sidebar

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#31]
I am very fond of calling my script filters from external triggers and since all the Script Filters are generated right next to the side, I get this little mess: 

![2017-12-12 at 00 42](https://user-images.githubusercontent.com/6391776/33859686-662ed638-ded5-11e7-9d8c-9dfcc12a09d2.png)

If you could generate the script filters like in previous Searchio with some space left:

![2017-12-12 at 00 43](https://user-images.githubusercontent.com/6391776/33859721-8179d2f8-ded5-11e7-8f4b-0bc78e38346c.png)

It would be really useful. Other users can also use this space to make Hotkey triggers or something else. 

Thank you.

**Comment by nikitavoloboev** [comment]
Bonus points is if you could generate the script filters with an external trigger attached. I can give a go at adding this and sending a PR if you are willing to accept it.

**Comment by deanishe** [comment]
I'll consider moving everything over to the right to leave space for Hotkeys.

I'm not going to add generation of External Triggers because I don't see much point to them.

Fallback Searches are on the list, though.

**Comment by nikitavoloboev** [comment]
Thank you. 

Also pragmatic generation of Script Filters and other objects is really interesting. I think this is the first workflow that does this and there is so many cool things you can do with this.

**Comment by deanishe** [comment]
> I think this is the first workflow that does this

It's not. I did it a long time ago with [Fuzzy Folders](https://github.com/deanishe/alfred-fuzzyfolders).

There are a few downsides to it, notably that Alfred doesn't notice immediately if `info.plist` has changed.

**Comment by deanishe** [comment]
I've added additional space to the left to insert a Hotkey or External Trigger.

**Comment by nikitavoloboev** [comment]
Thank you. I was wondering. Would updating the workflow reset all the generated script filters?

**Comment by nikitavoloboev** [comment]
Oh I see now `Reload` action. That's pretty neat.

**Comment by deanishe** [comment]
Read first, then post…
