### ISSUE TITLE
Only add script filters to the end

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#34]
Is it possible to always add generated script filters to the end?

The reason I ask is because I added `simple wikipedia` search and it added it not to the end but in the middle like so: 

![2017-12-15 at 19 45](https://user-images.githubusercontent.com/6391776/34055658-8cbf31be-e1d0-11e7-9ffd-0bfff95c29ac.png)

And the additional triggers I set are misaligned. You can imagine that users may have hotkey triggers instead of external but the issue will still be there.

I hope you will consider adding this. Thank you.

**Comment by deanishe** [comment]
> Is it possible to always add generated script filters to the end?

In theory, probably, but it would be a lot of work.

Currently, the workflow simply deletes all the Script Filters it has created, and then creates new ones for all of the configured searches.

Trying to figure out which Script Filters don't need updating would be very complicated compared to nuking-and-replacing them all, especially as the `reload` command also functions as a way to fix Script Filters you've fucked up, or to reset after an update has changed the way they work.

There's already enough complexity for my tastes in getting the JSON configuration format right.

I *may* make the rewrite smarter, but as I've said before: your love of attaching External Triggers to everything is your cross to bear, not mine.

Don't hold your breath.
