### ISSUE TITLE
Case-sensitivity on wikia searches

### ISSUE THREAD

**Issue by therockmandolinist** [deanishe/alfred-searchio#4]
Had posted this to alfredforum, probably better to post here:

I'm experiencing some weird behavior where wikia searches are oddly case sensitive - for example, when searching in tardis.wikia.com, a search for "tenth doctor" with searchio will not show results, whereas "tenth Doctor" will. Or, for dc.wikia.com, night-owl vs night-Owl behaves in the same way.

**Comment by deanishe** [comment]
I'm afraid that's almost certainly entirely out of my control: it's Wikia's API that's behaving that way. It's possible that I've overlooked some parameter that specifies whether the search is case-sensitive or not, but that would be very unusual.

Perhaps you could report the issue to them, as it is pretty daft behaviour by their search system?
