### ISSUE TITLE
2.0.0-rc1 ver. fails due to no file

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#41]
I just got new mac and decided to try 2.0.0-rc1 again to see if I actually get faster speeds than python version.

I get this error though running the g trigger to search Google.

15:45:37 workflow.go:760: [ERROR] open /Users/nikivi/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-searchio/searches/google-en.json: no such file or directory

Anything I should of done to set the file up?

**Comment by nikitavoloboev** [comment]
Never mind I'm being silly again. I had to 'Reload' the thing. It was just confusing because as I installed the workflow I had a bunch of script filters in place already. I believe it should be empty as default.

**Comment by nikitavoloboev** [comment]
Or in the case of such error happening to user:

15:45:37 workflow.go:760: [ERROR] open /Users/nikivi/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-searchio/searches/google-en.json: no such file or directory

Maybe it is best to offer reloading the configuration or do it automatically for the user.

**Comment by peng051410** [comment]
+1
