### ISSUE TITLE
v2: Allow to search fallback result

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#42]
Allow users to press return to search a query that is not part of suggested results like here:

![2018-08-16 at 14 19](https://user-images.githubusercontent.com/6391776/44208010-73b4e480-a15f-11e8-89fe-a74e7ab3eaf8.png)

**Comment by deanishe** [comment]
I don't understand what you want.

**Comment by nikitavoloboev** [comment]
If you search something and reach a point where there are no Google suggestions, you can't press return on the query you typed.

**Comment by deanishe** [comment]
Same as #44 in practice.
