### ISSUE TITLE
v2: Allow pressing tab to expand queries

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#43]

**Comment by deanishe** [comment]
It already does.

**Comment by nikitavoloboev** [comment]
I am on `v2.0.0-rc1`

![2018-08-24 at 12 27](https://user-images.githubusercontent.com/6391776/44580130-10e3ce80-a799-11e8-9788-375c3b494379.png)

And it doesn't for me. Pressing tab here does nothing.

![2018-08-24 at 12 28](https://user-images.githubusercontent.com/6391776/44580153-340e7e00-a799-11e8-8d31-131ef4e70eff.png)

**Comment by deanishe** [comment]
Duplicate of *your own* issue #32
