### ISSUE TITLE
v2: Provide user query itself

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#44]
I would personally prefer it as first query or ideally make it configurable so its either always last result or first result (i.e. when you search Safari user query always takes precedence and you have to down arrow to go to google results).

#33 mentions that it won't be added however but at least query as last result was in the plans.

**Comment by deanishe** [comment]
The last result is already the query.

**Comment by nikitavoloboev** [comment]
Not in `v2.0.0-rc1`. Was there a new version released? I don't see it in releases.

**Comment by deanishe** [comment]
> Was there a new version released?

No. It's in develop. Stop posting duplicate issues. Especially of your own issues.

**Comment by nikitavoloboev** [comment]
My bad. Going to try and fix my own issues now that I got `develop` branch running.
