### ISSUE TITLE
Add ability to copy evaluated link from Google Lucky Search

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#48]
Often when writing something I want to hyperlink something and I know that if I google for it, it will be the first result shown so instead of doing Google Lucky search, opening URL, copying URL, closing tab. I want to be able to search for a query with Google suggestions and on pressing copy or some key, put the actual URL that Google Lucky evaluates to, to my clipboard or paste it. That would be awesome.

Although I understand that this is most certainly impossible to achieve due to the way the workflow is built now. I might try to extract the 'search and suggestion' part from this workflow and solve this specific use case in a dedicated workflow. Do you think that's wise? @deanishe

**Comment by deanishe** [comment]
https://github.com/deanishe/alfred-resolve-url
