### ISSUE TITLE
Give option to always present the fallback query even before results are fetched

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#49]
How difficult would it be to move the fallback search as first result in Searchio and have it always be present. Right now when you search for something, there is a slight amount of seconds where I actually see something as a result. Be it results from Google or the fallback query. 

I would love to have an option to make the fallback search the first item in the list, always present. And then fetch and present suggestion results as result 2/3/...

I get issues like this otherwise:

![2018-10-03 at 14 14](https://user-images.githubusercontent.com/6391776/46409725-df0a4400-c716-11e8-9644-7620e3fc8a7d.png)

![2018-10-03 at 14 16](https://user-images.githubusercontent.com/6391776/46409778-03feb700-c717-11e8-9c0a-4f9618d05277.png)

It's not consistent. I often make Google searches where I know the exact string I want to search on and I want to do it fast, type instantly, press return without waiting a little for results to fetch nor press the up arrow and hope the fallback will be there. 

Old Searchio allowed for this use case and it was perfect. But I don't want to go back to slower Python version. I can attempt to solve this myself if you think it's possible.

Thank you.

p.s. Show Query in Results is active

![2018-10-03 at 14 19](https://user-images.githubusercontent.com/6391776/46409885-593ac880-c717-11e8-9bf8-f51512da4d20.png)

**Comment by nikitavoloboev** [comment]
If it's out of scope for this workflow, I'll make my own fork then. I just don't want to keep up with changes you make to Searchio and my fork to keep it in sync. 😞

**Comment by deanishe** [comment]
> present the fallback query even before results are fetched

How is the workflow supposed to return results before it has any results?

> How difficult would it be to move the fallback search as first result in Searchio and have it always be present

It's extremely easy to do, but as you must know by now, you have to turn off Alfred's knowledge to force results to appear in a certain order.

The workflow is working as expected. If your query already appears in the results, the workflow doesn't add another duplicate result at the end.

> I often make Google searches where I know the exact string I want to search on and I want to do it fast, type instantly, press return without waiting a little for results

Then use Alfred's built-in web searches instead.

The *whole point* of this workflow is to fetch and show you suggestions. If you don't want to wait for them, why use the workflow?

> I just don't want to keep up with changes you make to Searchio and my fork to keep it in sync

I hardly ever make any changes to the workflow.

If other people would also like this feature, I'll consider it.

But your "I don't want to wait or look at the suggestions" argument is invalid because the whole point of the workflow is to show you search suggestions…

**Comment by nikitavoloboev** [comment]
> How is the workflow supposed to return results before it has any results?

Yeah I just realized you are right. For some reason I thought you could present one item (the query) always as result whilst it is fetching for things to fill in the other items. That's a shame.



> turn off Alfred's knowledge

But what Alfred knowledge do you need in this case? There is no remembering of what user chose before because each query is unique. Unless I misunderstand something.



> If your query already appears in the results, the workflow doesn't add another duplicate result at the end

The issue here is inconsistency. And it's a big issue because I don't want to wait for results to load, then see 'hey Google gives my fallback as a result, I should down arrow. Or hey it doesn't, down arrow it is.'.

 

> Then use Alfred's built-in web searches instead

I don't want to do that. Because I want one interface to do my 'suggestion powered searches'. Just cover the use case of me simply searching for whats in my head now and also the case of me looking at suggestions if I wish. Basically the default URL searching behavior (which Python Searchio version accommodated).



> argument is invalid

It's valid for me. I am surprised you don't find this annoying as much as I do. I will try to get a fork working and turn off Alfred's knowledge because I am not sure how it is useful in here. I mean if Python Searchio could do it, then Go version should do it too. And I didn't notice any issues when I was using the first result as always my query.

**Comment by deanishe** [comment]
> because each query is unique

How do you come to that conclusion?

> Unless I misunderstand something

Well for one thing, using Alfred's knowledge means that if I use Alfred's history to re-run the search, the result I chose will now (almost always) be the first result.

> I don't want to wait for results to load, then see 'hey Google gives my fallback as a result, I should down arrow. Or hey it doesn't, down arrow it is.'.

I don't understand.

> I am surprised you don't find this annoying as much as I do

That's because I watch what the workflow is doing, so I don't have to type more than necessary. In your example above, I would *never* enter "react element". I would stop at "react elem" and check the results.

**Comment by nikitavoloboev** [comment]
> How do you come to that conclusion?

Well the query may not be unique. But results fetched from Google will always be presented in the same order I would think. Alfred shouldn't mess with that. So I don't see where 'Alfred's knowledge' is being used here. I thought Alfred knowledge was about remembering what you picked in your results and surfacing those to the top. But with Google or suggestion searches you want Google to decide that for you. (I would think)





> if I use Alfred's history to re-run the search

Makes sense why you want to keep it then. I run all my workflows from external triggers (recently [moved my Karabiner config](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/karabiner.edn) to be generated with a [cool DSL](https://github.com/yqrashawn/GokuRakuJoudo)) so I never use the Alfred search history.



> I don't understand.

Well the big issue is that I can't with confidence quickly go to my fallback. Because if it's in the Google results, fallback won't be as last result (it will be part of results so I have to scan through results to see if that's the case before deciding on how do I actually run my raw query). 

Hope that makes sense.

**Comment by nikitavoloboev** [comment]
Also I find it annoying how I can't quickly up arrow as results are being fetched. Because once they finish fetching, the first result in Alfred will be highlighted again. 

I might just use Python Searchio for now as I lose more time due to this issue than what Go speed improvements bring sadly. 😞

Will read through the code fully and hopefully solve this for myself as I understand why you don't want to add this. As you use Alfred search history feature.

**Comment by deanishe** [comment]
> Because once they finish fetching, the first result in Alfred will be highlighted again.

Yes. That's how Alfred works.

> I understand why you don't want to add this

It's not that I don't want to add it. It's that I won't add it in a way that causes other problems or fucks up the workflow for other people who use Alfred normally. Which is something you don't seem to consider properly before submitting requests.

I think I can force the query to always be the last item, but that screws up the history for the case that the entered query is the result the user used.

It might be possible to do by filtering the API results and adding an option to disable Alfred's knowledge.

**Comment by deanishe** [comment]
>  I am going to try make the user query the **first item**, not the last. Will submit a PR

Then I will reject the PR unless you make first place optional behaviour.

**Comment by nikitavoloboev** [comment]
Will try make it optional. If not, I'll use the fork.

Thank you for your comments.

**Comment by nikivdev** [comment]
Amazing! Thank you a lot @deanishe ❤️

Congrats on the v2 release 🎊

**Comment by nikivdev** [comment]
p.s. I now get why you like to have user query as last item. Before I nearly always typed the entire query myself unless its something complex and I needed suggestions. But the trick is to actually always wait for suggestions even for small queries that are few word if not one.

Pretty happy about v2 now that I got this epiphany.

**Comment by deanishe** [comment]
> But the trick is to actually always wait for suggestions even for small queries that are few word if not one

Well, yeah. That is kind of the whole point of the workflow…

**Comment by nikivdev** [comment]
Solved my issue with not being able to quickly search my exact query (wait until results load + up arrow) with km macro.

![2018-10-15 at 07 03](https://user-images.githubusercontent.com/6391776/46930854-8a38c880-d048-11e8-91e4-b0ee4550ae63.png)

Bound to [b + k](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/karabiner.edn#L423). Where as [Searchio is bound to jk](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/karabiner.edn#L78). It's super fast. ✨
