### ISSUE TITLE
Fresh install, default workflows don't work, google-en.json: no such file or directory

### ISSUE THREAD

**Issue by episage** [deanishe/alfred-searchio#53]
Hi, it is a fresh alfred-searchio installation. Downloaded from releases from this repo. 
No workflow works for me because of the errors:

When I do searchio reload it destroys all the scripts that I wanted to use (`g <query>` for google search for example).
![image](https://user-images.githubusercontent.com/2196095/53680666-ceb6bf00-3cde-11e9-80f5-dbf64f5ca69e.png)
![image](https://user-images.githubusercontent.com/2196095/53680671-e55d1600-3cde-11e9-9c11-f808291c229b.png)

What am I doing wrong?

OS:
![image](https://user-images.githubusercontent.com/2196095/53680583-05400a00-3cde-11e9-8228-683e16a1c055.png)

Searchio version:
![image](https://user-images.githubusercontent.com/2196095/53680608-43d5c480-3cde-11e9-84e7-7b4ad082ea3c.png)

Error:
![image](https://user-images.githubusercontent.com/2196095/53680615-5b14b200-3cde-11e9-9ab9-730324f6f52b.png)

Debug log SS:
![image](https://user-images.githubusercontent.com/2196095/53680654-9d3df380-3cde-11e9-8167-3ccf43168edd.png)

Debug log:
```
[2019-03-02 11:30:03][ERROR: input.scriptfilter] Code 1: 🍺
11:30:03 workflow.go:304: --------- Searchio!/2.0.1 (AwGo/0.14.0) ----------
11:30:03 search.go:127: loading search from /Users/epi/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-searchio/searches/google-en.json ...
11:30:03 feedback.go:453: Sent 1 result(s) to Alfred
11:30:03 workflow.go:352: [ERROR] open /Users/epi/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-searchio/searches/google-en.json: no such file or directory
11:30:03 workflow.go:380: ------------------- 1.369401ms -------------------
```

**Comment by episage** [comment]
I found a workaround. 
You have to do `searchio` -> `reload`
Then you have to create all the search commands manually using 
![image](https://user-images.githubusercontent.com/2196095/53680773-46d1b480-3ce0-11e9-9302-dba08f4d4e60.png)
![image](https://user-images.githubusercontent.com/2196095/53680775-4f29ef80-3ce0-11e9-92f8-339ce20c8b64.png)
![image](https://user-images.githubusercontent.com/2196095/53680783-58b35780-3ce0-11e9-83c8-9700be6f62db.png)
![image](https://user-images.githubusercontent.com/2196095/53680788-64068300-3ce0-11e9-9632-8cc1866974a8.png)
![image](https://user-images.githubusercontent.com/2196095/53680797-7b457080-3ce0-11e9-8905-b8071b8dd769.png)

**Comment by deanishe** [comment]
I'm going to close this in favour of #54 (same problem). I'll have a think about how best to solve it.
