### ISSUE TITLE
Potential for showing Google results in Alfred

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-searchio#56]
Came across [SerpApi](https://serpapi.com). By looks of it would allow to pragmatically get the results of Google search result pages without parsing the HTML yourself and keeping that parser up to date. You can rely on their service.

Curious if you would consider adding support for it. Although the Pricing is quite steep. 

It has both [Python](https://github.com/serpapi/google-search-results-python) & [Go](https://github.com/serpapi/google-search-results-golang) wrappers for easy access.

**Comment by deanishe** [comment]
Lol. Who's going to pay for that?

The answer is "no". I'm not going to integrate an SDK just for a single search engine. If an engine can't be defined using the JSON configuration format, I don't want it, tbh.

Perhaps you could build your own webapp that exposes Google search results via the OpenSearch API?
