### ISSUE TITLE
Google Search - Certificate Signed by Unknown Authority

### ISSUE THREAD

**Issue by bheus** [deanishe/alfred-searchio#57]
I noticed this morning that Google Searches are failing.  It looks like there is a certificate error.  Searches with other engines like DuckDuckGo are working as expected.

```
[11:54:37.254] Searchio![Script Filter] Script with argv 'test' finished
[11:54:37.260] ERROR: Searchio![Script Filter] Code 1: 🍺
11:54:36 workflow.go:304: --------- Searchio!/2.0.1 (AwGo/0.14.0) ----------
11:54:36 search.go:127: loading search from /Users/{USER}/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-searchio/searches/google-en.json ...
11:54:36 search.go:224: querying "Google (English)" for "test" ...
11:54:37 feedback.go:453: Sent 1 result(s) to Alfred
11:54:37 workflow.go:352: [ERROR] couldn't reload data: Get https://suggestqueries.google.com/complete/search?client=firefox&q=test&hl=en: x509: certificate signed by unknown authority
11:54:37 workflow.go:380: ------------------ 259.973241ms ------------------
[11:54:37.262] Searchio![Script Filter] {
  "variables": {
    "AW_SESSION_ID": "BYQWN7R0V050B3TQ5CDT2POE"
  },
  "items": [
    {
      "title": "couldn't reload data: Get https://suggestqueries.google.com/complete/search?client=firefox\u0026q=test\u0026hl=en: x509: certificate signed by unknown authority",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
```

**Comment by deanishe** [comment]
What version of macOS are you running? Can you open this URL in Safari?

```
https://suggestqueries.google.com/complete/search?client=firefox&q=test&hl=en
```

Does this command work in Terminal?

```
/usr/bin/curl 'https://suggestqueries.google.com/complete/search?client=firefox&q=test&hl=en'
```

This doesn't look like a problem with the workflow: it uses your system's root SSL certificates to verify HTTPS connections. If they're valid, the workflow should work.

You can also check in the Keychain Access app: Look under "System Roots" for certificates with a name like "GTS Root". Check if any are expired.

**Comment by bheus** [comment]
Thank you for your help.  I didn't have any expired certs and the command was working as expected.  I tried disconnecting from my company's VPN and that seemed to have fixed it!  I reconnected and everything is still working!  I don't quite understand it, but now I know that my company's VPN could cause certificate errors in the future.  Thank you again for your help!
