### ISSUE TITLE
macOS not allowing script to be run (cannot be verified)

### ISSUE THREAD

**Issue by bowernite** [deanishe/alfred-searchio#61]
![Screen Shot 2020-12-01 at 8 16 19 AM](https://user-images.githubusercontent.com/16885191/100751945-93fb2280-33ad-11eb-9f4b-b7c1aaea5e91.png)

On macOS Catalina 10.5.6

**Comment by nikivdev** [comment]
Try [this](https://github.com/deanishe/awgo/wiki/Catalina)

**Comment by bowernite** [comment]
@nikitavoloboev Awesome, thank you! This worked for me 🙂
