### ISSUE TITLE
Autosuggest for Google Maps broken

### ISSUE THREAD

**Issue by altern8tif** [deanishe/alfred-searchio#8]
Seems like the autosuggest for Google Maps no longer works.  Did the Google API endpoint change for that?

![screen shot 2016-11-27 at 8 25 36 pm](https://cloud.githubusercontent.com/assets/5793364/20648376/bd0359b4-b4df-11e6-82cd-3051d15ba8e2.png)

**Comment by deanishe** [comment]
Could you post the error log from the debugger (if there is one)? A screenshot isn't much help. Thanks.

**Comment by altern8tif** [comment]
I've put the debugger output into a [gist](https://gist.github.com/altern8tif/67520c86f03484a5da706dff0b17e1aa).

**Comment by altern8tif** [comment]
Is this due to the requests exceeding the Google Maps API free limits?

**Comment by deanishe** [comment]
Doubtful unless you're going crazy on Google Maps.

I haven't looked into the issue yet, as I've been really busy with work.

Hopefully, I'll be able to get it fixed on Thursday.

**Comment by altern8tif** [comment]
@deanishe sure thing 👍 

Was poking around a little bit but not familiar enough with Python to find where the bug is...

**Comment by deanishe** [comment]
I've sorta fixed this.

The maps autosuggest API has been turned off, so I've replaced with with the Places API. The upshot is, you need to get an API key for that one :(

Google Maps is working on the `develop` branch, but some engines are still missing or half-implemented.

**Comment by deanishe** [comment]
Fixed in [v2.0.0-rc1](https://github.com/deanishe/alfred-searchio/releases/tag/v2.0.0-rc1).
