### ISSUE TITLE
Would be really useful to have a modifier action for Google / Youtube to make a search by week

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#9]
So for example I make a search through the workflow and instead of pressing return, I can press control + return and it would instead filter the Google search by 'this week'. This option : 

![2017-01-13 at 19 54](https://cloud.githubusercontent.com/assets/6391776/21941662/22881928-d9ca-11e6-869c-87e247b2b6c3.png)

I have a regex that I use to quickly turn a google search into a 'search by this week' that I very often use : https://regex101.com/r/Zzof5b/2 

And I just think it would be really nice to add an extra action to Searchio itself so users have more control over the searches they make.

This same concept can be applied to Youtube, DuckDuckGo or Amazon's option to filter by price : 

![2017-01-13 at 19 56](https://cloud.githubusercontent.com/assets/6391776/21941723/7683991c-d9ca-11e6-936a-c2ad8735016b.png)

Currently you can just do a replace action on the output with the regex : 

![2017-01-13 at 20 00](https://cloud.githubusercontent.com/assets/6391776/21941831/e452dd9a-d9ca-11e6-9f8d-c2a194d09add.png)

But then if I would update a workflow, I would lose all these actions. Do you perhaps want to add some of these 'extra' actions to Searchio in the future? 

I also think it would be nice to calculate these links in the workflow code itself rather then manipulating the end urls with regex. I tried adding something like this but didn't manage to get very far with it. :(

Thank you for this amazing workflow.

**Comment by nikitavoloboev** [comment]
Just as a note, having this kind of modifier support for search workflow is so very useful. I have started to add it to all my external triggered web searches. 

![2017-01-14 at 16 05](https://cloud.githubusercontent.com/assets/6391776/21955846/5dee8548-da73-11e6-9c98-80b91ab623bb.png)

However all these searches are static in the sense that there are no autosuggestions there. I just filter out searches with modifiers. Adding this modifier key support to this workflow is a lot trickier.
If you can guide me in a direction of what I can change to try add such support, I will try my best to add it. :)

Thank you.

**Comment by deanishe** [comment]
> Do you perhaps want to add some of these 'extra' actions to Searchio in the future?

No. Well beyond the scope of the workflow.
